---
title: Review for the manuscript "Hydro-Climatic Modelling of an Ungauged Basin in
  Kumasi,Ghana"
output:
    pdf_document:
      keep_tex: true
---

# Manuscript summary

The manuscript presents an application of the Soil and Water Assessment Tool (SWAT) to simulate water balance components, such as discharge, actual evapotranspiration, and soil and ground water for the ungauged Owabi catchment in Ghana. Provided that I comprehended the content of the present manuscript correctly, the main goal of the study was to assess the impact of the future climate change and the future land use change on the water resources of the Owabi catchment. The study covers the following working steps to enable an impact assessment of climate change and land use change on the catchment's water resources:

- Climate change scenarios and land use change scenarios were developed for the study region. The development of the climate change scenarios included a bias correction of the mean monthly rainfall, and the mean monthly min/max temperatures of the implemented climate change scenarios.

- Implementing openly available data products (elevation, land use, and soil), a SWAT model was set up for the study region. Local monthly precipitation and temperature data was employed to run the model and to simulate monthly mean discharge at the catchment outlet and other water balance components averaged for the study area.

- Observation data for the discharge leaving the catchment, but also data on other water balance components are not available. Hence, the authors transferred monthly discharge records from the neighboring Offin catchment applying regionalization by physical similarity of the catchments and employed the discharge records to calibrate the model parameters of the SWAT model set up for the Owabi catchment.

- Parameter sensitivity analysis and model calibration of the set up SWAT model was performed using the software SWAT-CUP and employing the method SUFI-2 that is available from SWAT-CUP considering multiple objectives for the mean monthly discharge at the catchment outlet.

- All combinations of developed climate scenarios and land use scenarios were implemented into the calibrated SWAT model mean monthly discharge was simulated for the near future period from 2021 to 2050.

The general setting of this study, that the catchment is essential for water supply in the surrounding urban areas, that land use change bears a potential risk to deteriorate the water resources, and that the availability of environmental data is very limited to draw conclusions, clearly illustrates the relevance of such work to be a bench mark study for water management in this region (and other regions with a similar setting). In my opinion however, this manuscript requires substantial work, before considering it for any publication. In its present form I recommend to reject the manuscript. Following, I comment on the parts of the manuscript that require clarification and on which I base my recommendation. In the first section I outline my general comments on the manuscript. These points that I see as very critical for the manuscript, that are missing or that were completely unclear to me. The following section addresses specific issues I have with parts of the manuscript such as figures or specific paragraphs. In my comments I will also refer to issues addressed in the reviews of the previous version of the manuscript, as I fully agree with several points that were already, but still remain unanswered (or insufficiently answered) in the previous version of the manuscript.

# General comments

- **The specific focus of the manuscript:** This point was already addressed in a previous review and I fully agree with this point. As I tried to summarize in the previous section, the work involves many working steps to. Every single working steps is however not novel in itself, but rather an application of existing methods, that subsume to a comprehensive impact study. In its present form I agree that the manuscript is not appropriate for publication in HESS. I see however a potential to focus on one of the aspects presented in the manuscript (e.g. issues with the regionalization, individual impacts and combined impacts of climate change and land use change) and analyze that with great detail, to derive novel findings.

- **Manuscript structure, grammar and spelling:** The structure of the manuscript is hard to follow in its present form. The abstract and the introduction do not clearly state the actual goal of the study. I see that goals are mentioned in the text. But they are mentioned in between loosely structured lists of tasks that were done to perform this study. I advise the authors to clearly state the hypotheses of the study! What were the research questions and what were  findings that address and answer these (E.g. if the issue of water supply under the impact of climate and land use change was the focus, which conclusions can be drawn from the simulations based on the available water for water supply in the near future?). The manuscript clearly requires proof reading. The manuscript contains many spelling and grammar mistakes, to make it inappropriate for prublication in its present form!

- **The choice of GCM-RCM combinations:** For environmental impact studies that consider future climate change it is essential that the future simulations of precipitation and temperature (provided by the climate scenarios) cover i) a wide range of possible future climates for a region and ii) provide them on the operable scale. i) Thus, a widely applied procedure is to implement the simulations of different GCM-RCM combinations in the impact analysis. Different GCM-RCM combinations follow different trajectories into the future and therefore can result in substantially different results for future precipitation and air temperatures. To only consider one GCM-RCM product can strongly bias the simulation results of the impact assessment. Thus I fully agree with the comments from the reviews of the previous version of the manuscript, that this issue must be analyzed. Yet, I think that the revised manuscript does not answer this question. ii) In a reply the authors mention that the updated spatial resolution of the implemented GCM-RCM simulations is ~ \(25km\). Consequently, the area of a pixel of the GCM-RCM simulations is ~  \(625 km^2 \). Thus, the area of the entire Owabi catchment is with ~ \(69 km^2\) only a tenth of a single pixel (letting aside the skillful scale of the GCM-RCM simulations) and the GCM-RCM simulations do not cover the spatial characteristics of this region by far!

- **The transfer of discharge observations:** The application of the regionalization of discharge observation data from a neighboring catchment to apply these data for calibration of the study catchment is very poorly documented. It is not satisfactory to refer to the general method, but it is much more essential for this work that the working steps in this particular case study are documented in detail. The authors mention similarity indices that were applied for the transfer of the discharge observation data. Yet, no details on the transfer of the data is given. For me as a reader it is not clear if the discharge of the donor catchment (that is substantially larger) was transferred as specific discharge (in \(mm\) and considering the ratio in area) or if the raw discharge records (\(cm^3 s^{-1}\) were implemented. This section requires substantial revision. I strongly advise to clarify the working steps that the authors performed in the regionalization of discharge. How did the physical similarity indices affect the regionalization (e.g. in tables or text)? How does the initial time series of the discharge look like and what is the resulting time series of discharge used for the model calibration (e.g. show both time series)? Did the authors analyze the time series of precipitation for both catchments (if even possible based on the data availability)? A map that shows both catchments would strongly improve the manuscript. From a methodological perspective I also think that a more sound way for calibration would have been to set up a SWAT model for the larger catchment, calibrate the model parameters and transfer these parameter to the smaller catchment.

-
